apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: senanalytics-ingress
  namespace: senanalytics
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - mission-control.senanalytics.com
        - api.senanalytics.com
      secretName: senanalytics-tls
  rules:
    - host: mission-control.senanalytics.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 3000
    - host: api.senanalytics.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 8001
